name: app_panaderia
description: "Aplicación de Panadería"
publish_to: 'none'

version: 1.1.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.1
  cloud_firestore: ^4.9.5
  url_launcher: ^6.1.0
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.2.3
  geolocator: ^11.0.0
  http: ^1.1.0
  flutter_map: 6.0.0
  latlong2: 0.9.0
  image_picker: ^1.0.4
  firebase_storage: ^11.7.7
  google_fonts: ^6.2.0
  sensors_plus: ^7.0.0
  flutterfire_cli: ^1.3.1
  flutter_admin_scaffold: ^1.4.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  camera: ^0.10.5
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/imgLogo.png
    - assets/splash_logo.gif
    - assets/model.tflite
    - assets/labels.txt

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgLogo.png"
  adaptative_icon_background: "#ffffff"
   