name: app_panaderia
description: "Aplicación de Panadería"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.1
  cloud_firestore: ^4.14.0
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
   